spring:
  application:
    name: gateway
  cloud:
    config:
      profile: dev
  config:
    import: configserver:http://localhost:8888

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true